#!/usr/bin/env python3

import rospy
from sensor_msgs.msg import JointState

from markers import *
from proy_functions import *

if __name__ == '__main__':

  rospy.init_node("testForwardKinematics")
  pub = rospy.Publisher('joint_states', JointState, queue_size=1)
  bmarker = BallMarker(color['GREEN'])

  # Joint names
  jnames = ['rev1', 'rev2', 'rev3','rev4', 'rev5', 'rev6','slider9','slider10']
  # Joint Configuration
  #q = [0, 50, 0, 50, 0, 50]
  q = [1, -0.3 ,1.6, 1.4, 1, 0.5, 0, 0]

  # End effector with respect to the base
  T = fkine_mh5lsii(q)
  print( np.round(T, 3) )
  bmarker.position(T)
  print('Obtained value:\n', np.round(T,3))
  # Object (message) whose type is JointState
  jstate = JointState()
  # Set values to the message
  jstate.header.stamp = rospy.Time.now()
  jstate.name = jnames
  # Add the head joint value (with value 0) to the joints
  jstate.position = q

  # Loop rate (in Hz)
  rate = rospy.Rate(20)
  # Continuous execution loop
  while not rospy.is_shutdown():
    # Current time (needed for ROS)
    jstate.header.stamp = rospy.Time.now()
    # Publish the message
    pub.publish(jstate)
    bmarker.publish()
    # Wait for the next iteration
    rate.sleep()
